### ISSUE TITLE
FileObject <- 이거 말이죠..?

### ISSUE THREAD

**Issue by KangDroid** [Navi-Cloud/Navi-Storage#1]
지금 FileObject가 대충 카테고리를 직접 스트링으로 넣어주고 있는데 

그냥 String 타입 말고 Category 타입을 넣는건 어떨까요? 몽고에서 받아주지 않을까 하는 생각입니다.

LastModifiedTime같은 경우에는 서버에서 저장도 하지만, 클라에서 저걸 분석해야 되는거라 string으로 넘겨버리면 약간 자유도가 너무 떨어지지 않나 생각이 듭니다. 가령 Timestamp로 하면 클라이언트에서 시간을 어디까지 보여줄 지 결정이 가능한데 string으로 넘기면 딱히 방법이 없어서요!

@0JIEUN0

**Comment by 0JIEUN0** [comment]
오 serialize 할거를 생각하다가 저렇게 한 것 같은데 코멘트 주신 걸 바탕으로 수정해보겠습니다!
리뷰 감사합니다 👍

**Comment by 0JIEUN0** [comment]
[category] String -> Category (enum)
[lastModifiedTime] String -> Date
by cb8045d
